version: '3'

volumes:
  laravel-redis-data:
#  laravel-db-data:

networks:
  laravel:
    driver: bridge

services:
  api:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./.:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - db
      - redis
      - mailhog
    networks:
      - laravel

  db:
    image: mysql:5.7
    restart: always
#    volumes:
#      - laravel-db-data:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'Wtorek*****1992'
      MYSQL_DATABASE: 'logos'
      MYSQL_PASSWORD: 'Wtorek*****1992'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - laravel-redis-data:/data
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    hostname: 'laravel.api'
    ports:
      - "8082:80"
      - "444:444"
    volumes:
      - ./:/var/www
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - api
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1027:1025"
      - "8027:8025"
    networks:
      - laravel
